[package]
name = "udima-thesis"
version = "1.0.0"
entrypoint = "lib.typ"
authors = [
    "Luis Daniel Casais Mezquida <luisdaniel.casais@alumnos.udima.es>",
]
license = "Unlicense"
description = "Bachelor/Master's Thesis template for Universidad a Distancia de Madrid"
repository = "https://github.com/ldcas-uc3m/udima-thesis-typst"
compiler = "0.14.2"
keywords = ["udima", "thesis"]
categories = ["thesis"]
exclude = [".github", "docs", "examples", ".vscode", "template/report.pdf", "out"]

[template]
path = "template"
entrypoint = "report.typ"
thumbnail = "thumbnail.png"
